config/routes.rb
Rails.application.routes.draw do
  resources :pages
  root 'pages#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get '/resources', to: "pages#resources"
  get '/features', to: "pages#features"
  get '/process', to: "pages#process_page"
  get '/ordering', to: "pages#ordering"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/page.rb
class Page < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  before_action :set_page, only: [:show, :edit, :update, :destroy]

  # GET /pages
  # GET /pages.json
  def index
    @pages = Page.all
  end

  def resources
    @pages = Page.all
  end

  def features
    @pages = Page.all
  end

  def process_page
    @pages = Page.all
  end

  def ordering
    @pages = Page.all
  end

  # GET /pages/1
  # GET /pages/1.json
  def show
  end

  # GET /pages/new
  def new
    @page = Page.new
  end

  # GET /pages/1/edit
  def edit
  end

  # POST /pages
  # POST /pages.json
  def create
    @page = Page.new(page_params)

    respond_to do |format|
      if @page.save
        format.html { redirect_to @page, notice: 'Page was successfully created.' }
        format.json { render :show, status: :created, location: @page }
      else
        format.html { render :new }
        format.json { render json: @page.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pages/1
  # PATCH/PUT /pages/1.json
  def update
    respond_to do |format|
      if @page.update(page_params)
        format.html { redirect_to @page, notice: 'Page was successfully updated.' }
        format.json { render :show, status: :ok, location: @page }
      else
        format.html { render :edit }
        format.json { render json: @page.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pages/1
  # DELETE /pages/1.json
  def destroy
    @page.destroy
    respond_to do |format|
      format.html { redirect_to pages_url, notice: 'Page was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_page
      @page = Page.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def page_params
      params.fetch(:page, {})
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.slim
doctype html
html
  head
    title Penblades
    meta content="text/html; charset=UTF-8" http-equiv="Content-Type"
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  body
    = render "components/navbar"
    = yield
    = render "components/footer"

app/views/pages/_form.html.slim
= form_for @page do |f|
  - if @page.errors.any?
    #error_explanation
      h2 = "#{pluralize(@page.errors.count, "error")} prohibited this page from being saved:"
      ul
        - @page.errors.full_messages.each do |message|
          li = message

  .actions = f.submit

app/views/pages/edit.html.slim
h1 Editing page

== render 'form'

=> link_to 'Show', @page
'|
=< link_to 'Back', pages_path

app/views/pages/features.html.slim
.row.values-other
  .col-4.value-point-container
    .value-point.p-3
      .value-point-title.my-3 
        .image
          = image_tag('MedicalReport.svg')
        .text Value Point 2
        hr.value-splitter
      .value-point-content.my-3  This is a short blurb about a value statementakasdnfas alsdf a 
  .col-4.value-point-container
    .value-point.p-3
      .value-point-title.my-3 
        .image
          = image_tag('MedicalReport.svg')
        .text Value Point 2
      hr.value-splitter
      .value-point-content.my-3  This is a short blurb about a value statementakasdnfas alsdf a 
  .col-4.value-point-container
    .value-point.p-3
      .value-point-title.my-3 
        .image
          = image_tag('MedicalReport.svg')
        .text Value Point 2
        hr.value-splitter
      .value-point-content.my-3  This is a short blurb about a value statementakasdnfas alsdf a
  .request-sample.btn 
    .text Request a Sample 
    .chevron
      = image_tag('Chevron.svg')

.case-study
  .row
    .col-6.cut-padding
      = image_tag('Group.svg', class: 'group-image')
    .col-6.cut-padding
      .white
        .overlay
          .overlay-header Case Study
          hr.splitter
          .overlay-content Donec facilisis tortor ut augue lacinia, at viverra est semper. Sed sapien metus, scelerisque nec pharetra id, tempor a tortor. Pellentesque non dignissim neque. Ut porta viverra est, ut dignissim elit elementum ut. Nunc vel rhoncus nibh, ut tincidunt
      .orange

app/views/pages/index.html.slim
.container
  .row.my-3
    .col-3
      .overlay-top
        .overlay-header-top PenBlade is the safest scalpel on the market
        hr.splitter-top
        .overlay-content-top Keep your staff safe with the best safety scalpel on the market.
        .watch.video
          = link_to "Watch the Video", root_path
    .col-9
        = image_tag('Bitmap.svg', class: 'top-banner')

.container
  .row.values
    .col-md-6.col-lg-3.value-point-container
      .value-point.p-3
        .value-point-title.my-3
          .image
            = image_tag('Safety-Blue.svg')
          .text PREVENTS INJURIES
        hr.value-splitter
        .value-point-content.my-3
          .text Keeping your staff safe is our number one concern
    .col-md-6.col-lg-3.value-point-container
      .value-point.p-3
        .value-point-title.my-3
          .image
            = image_tag('Intuitive-Blue.svg')
          .text INTUITIVE DESIGN
        hr.value-splitter
        .value-point-content.my-3
          .text PenBlade uses the familiar penlike click on the top to activate
    .col-md-6.col-lg-3.value-point-container
      .value-point.p-3
        .value-point-title.my-3
          .image
            = image_tag('HQ-Blue.svg')
          .text HIGHEST QUALITY
        hr.value-splitter
        .value-point-content.my-3
          .text It is already used in operating rooms around the country
    .col-md-6.col-lg-3.value-point-container
      .value-point.p-3
        .value-point-title.my-3
          .image
            = image_tag('Surgeons-Blue.svg')
          .text PREFERRED BY SURGEONS
        hr.value-splitter
        .value-point-content.my-3
          .text The safest, easiest to use scalpel currentl on the market
    .request-sample-container
        a> href='#'
          span class="button-chev"
            | Request a Sample

.container
  .row.resources.m-auto
    .video-banner.m-3
    .how-to-order.m-3
      .how-to-order-title How to order
      hr.how-to-order-splitter
      .how-to-order-content Ordering for your facility is easy. Fill out a form and we will contact you shortly.
      .order-here
        a> href='#'
          span class="button-chev"
            | Order Here

    .resource.m-3
      .resource-title Resources
      hr.resource-splitter
      .resource-content Find GPO and Data Analysis Information here.
      .order-here
        a> href='#'
          span class="button-chev"
            | Contracts

.container
  .row.testimonials
    .col-6.accredidation
      .comment
        .avatar-container
          = image_tag('Avatar.svg', class: 'avatar')
        .content-container
          .name-container
            .name Name
            .accredidation Accredidcation
          .text "This is what this person thinks about PenBlade"
      .comment
        .avatar-container
          = image_tag('Avatar.svg', class: 'avatar')
        .content-container
          .name-container
            .name Name
            .accredidation Accredidcation
          .text "This is what this person thinks about PenBlade"
    .col-6.another-point
      .comment
        .container-text
          .image
            = image_tag('Features.svg')
          .text-container
            .text PenBlade is the easiest safety scalple available today. See how it works.
            hr.comment-splitter
        .link
          a> href='#'
            span class="button-chev-blue"
              | Contact Us
      .comment
        .container-text
          .image
            = image_tag('Mail.svg')
          .text-container
            .text Do you have a question, or would like to place an order? Contact us today.
            hr.comment-splitter
        .link
          a> href='#'
            span class="button-chev-blue"
              | Contact Us
.case-study
  .container
    .row
      .col-6.cut-padding
        = image_tag('Group.svg', class: 'group-image')
      .col-6.cut-padding
        .white
          .overlay
            .overlay-header Case Study
            hr.splitter
            .overlay-content Donec facilisis tortor ut augue lacinia, at viverra est semper. Sed sapien metus, scelerisque nec pharetra id, tempor a tortor. Pellentesque non dignissim neque. Ut porta viverra est, ut dignissim elit elementum ut. Nunc vel rhoncus nibh, ut tincidunt
        .orange

= render "pages/shared/images_section"

app/views/pages/new.html.slim
h1 New page

== render 'form'

= link_to 'Back', pages_path

app/views/pages/ordering.html.slim
/ TODO: Header Section
/ TODO: Include partial for 3-icon section
= render "pages/shared/images_section"

= render "pages/shared/contact_form"

app/views/pages/shared/_contact_form.html.slim
/ NOTE Just using an HTML form rather than rails form helpers because we're submitting to a salesforce endpoint
.container
  .row
    .col-5

      form action="https://webto.salesforce.com/servlet/servlet.WebToLead?encoding=UTF-8" method="POST"

        input name="oid" type="hidden" value="00D1I000002Mber"
        input name="retURL" type="hidden" value="http://www.penblade.com"

        .form-row
          .form-group
            label for="facility"  Facility
            input#facility.form-control maxlength="40" name="facility" size="20" type="text"
          .spacer
          .form-group
            label for="city"  City
            input#city.form-control maxlength="40" name="city" size="20" type="text"
          .spacer
          .form-group
            label for="state"  State
            input#state.form-control maxlength="20" name="state" size="20" type="text"

        .form-row
          .form-group
            label for="first_name"  First Name
            input#first_name.form-control maxlength="40" name="first_name" size="20" type="text"
          .spacer
          .form-group
            label for="last_name"  Last Name
            input#last_name.form-control maxlength="80" name="last_name" size="20" type="text"
          .spacer
          .form-group
            label for="title"  Title
            input#title.form-control maxlength="40" name="title" size="20" type="text"


        .form-row
          .form-group
            label for="phone"  Phone
            input#phone.form-control maxlength="40" name="phone" size="20" type="text"
          .spacer
          .form-group
            label for="email"  Email
            input#email.form-control maxlength="80" name="email" size="20" type="text"


        .form-row
          .form-group
            label More about us
            textarea#00N1I00000Dyq7J.form-control maxlength="255" name="00N1I00000Dyq7J" size="20" type="text"

        input.btn.btn-primary name="submit" type="submit"

        h4.form-info This form will submit through email.
        h4.form-info You will be contacted shortly.

app/views/pages/shared/_images_section.html.slim
.images
  .container
    .more-title More from PenBlade
    .row
      .col-4.bottom-image
        .image
          = image_tag('Bottom-type.svg', class: 'bottom-image')
        .more-sub
          .more-sub-title New Type Released
          .more-sub-content We are releasing PenBlade 2.5 with a new 1.2 cm blade.
          .more-link
            .link Read More
            .chevron
              = image_tag('Orange-chevron.svg')
          hr.more-splitter
      .col-4.bottom-image.my-auto
        .image
          = image_tag('Bottom-type.svg', class: 'bottom-image')
        .more-sub
          .more-sub-title New Type Released
          .more-sub-content We are releasing PenBlade 2.5 with a new 1.2 cm blade.
          .more-link
            .link Read More
            .chevron
              = image_tag('Orange-chevron.svg')
          hr.more-splitter
      .col-4.bottom-image.my-auto
        .image
          = image_tag('Bottom-type.svg', class: 'bottom-image')
        .more-sub
          .more-sub-title New Type Released
          .more-sub-content We are releasing PenBlade 2.5 with a new 1.2 cm blade.
          .more-link
            .link Read More
            .chevron
              = image_tag('Orange-chevron.svg')
          hr.more-splitter

app/views/pages/show.html.slim
p#notice = notice


=> link_to 'Edit', edit_page_path(@page)
'|
=< link_to 'Back', pages_path